### ISSUE TITLE
Unable to use terraform init

### ISSUE THREAD

**Issue by garethquantum** [bridgecrewio/terraform-aws-session-manager#1]
I've used the template in Terraform registry but when I perform a terraform init, all I get back is:

> Error: Module not found
> 
> Module "terraform-aws-session-manager" (from SSM.tf:1) cannot be found in the
> module registry at registry.terraform.io.

**Comment by jonjozwiak** [comment]
It looks like this was an error in the readme for the module source.  I've updated the readme.  Update your source and version and it will work: 

module "ssm" {
  source                    = "bridgecrewio/session-manager/aws"
  version                   = "0.2.0"
...
