### ISSUE TITLE
 Can't configure a value for "region"

### ISSUE THREAD

**Issue by samthakur74** [bridgecrewio/terraform-aws-session-manager#12]
Hello,
Using this module i am getting error
 Error: Value for unconfigurable attribute
 on .terraform\modules\ssm\main.tf line 58, in resource "aws_s3_bucket" "access_log_bucket":
58:   region                  = data.aws_region.current.name
Can't configure a value for "region": its value will be decided
automatically based on the result of applying this configuration.

Is this a known issue?

**Comment by taliesins** [comment]
```
locals {
  private_vpcs = local.delete ? [] : [
    for vpc in data.aws_vpc.main : {
      "id"       : vpc.id,
      "region"   : split(":",vpc.arn)[3]
    }
  ] 
}
```

Its possible to calculate the region from the arn of the vpc

**Comment by markl11** [comment]
Yes, having the same issue - not sure about the locals above - didn't help me with this module error.

**Comment by taliesins** [comment]
> Yes, having the same issue - not sure about the locals above - didn't help me with this module error.

Have a look at the PR I created. I have used this in a fresh setup with success.

**Comment by markl11** [comment]
Ok - version 0.2.0 is currently unusable. Trying to patch together a PR into version 0.2.0 is unfortunately no really doable - I don't want to spend too much time - after all modules should save time! Please publish a usable version as soon as possible. Thanks.
