### ISSUE TITLE
Module Doesn't Support Version 4.x of the AWS Provider

### ISSUE THREAD

**Issue by tkidd77** [bridgecrewio/terraform-aws-session-manager#16]
`apply` bombs when attempting to create S3 resources and instead needs to use the new S3 resources found [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration), [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration), [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning), and [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl).

Here are the respective errors thrown as these attributes are read only in aws provider v4 as [outlined here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket).

`Can't configure a value for "server_side_encryption_configuration": its value will be decided automatically based on the result of applying this configuration.`

`Can't configure a value for "lifecycle_rule": its value will be decided automatically based on the result of applying this configuration.`

`Can't configure a value for "versioning": its value will be decided automatically based on the result of applying this configuration.`

`Can't configure a value for "acl": its value will be decided automatically based on the result of applying this configuration.`

**Comment by JamesWoolfenden** [comment]
see v0.4.1

**Comment by tkidd77** [comment]
Works great, thanks.
